# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        tags: ${{ env.IMAGE_TAG }},latest
        image: ceczh/action-demo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: OpenShift Login
      uses: redhat-actions/oc-login@v1.1
      with:
        openshift_server_url: https://master.example.com:8443
        openshift_token: ${{secrets.OPENSHIFT_TOKEN}}
        insecure_skip_tls_verify: true
    - name: oc-new-app
      uses: redhat-actions/oc-new-app@v1
      with:
        app_name: actiondemo
        image: ceczh/action-demo:latest
        registry_hostname: docker.io
        namespace: bootsite
        registry_username: ${{ secrets.DOCKER_USERNAME }}
        registry_password: ${{ secrets.DOCKER_PASSWORD }}
